server:
  port: 7900
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  application:
    name: microservice-provider-user

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.liuwei: DEBUG
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}} # 服务注册表显示名
    lease-renewal-interval-in-seconds: 30 #请求服务注册间隔
    appname: microservice-provider-user #注册到EUREKA服务中的app名称，没配置默认是spring.application.name
    #hostname: user