server:
  port: 8010
  
spring:
  application:
    name: microservice-consumer-movie-ribbon-properties-customizing
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}}
    
ribbon:
  eureka:
   enabled: false
   
microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900
    